DROP TABLE IF EXISTS verses;
DROP TABLE IF EXISTS translations;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS versifications;
DROP EXTENSION IF EXISTS "pg_trgm";
DROP EXTENSION IF EXISTS "uuid-ossp";
